### ISSUE TITLE
Not able to show the google analytics reports on my dashboard

### ISSUE THREAD

**Issue by Mohinesh27** [flyacts/ngAnalytics#1]
Hello sir,
I have implemented the code as per demo.html which i have found in downloads of ngAnalytics but I am not getting from where i get the view id 'ga:81197147'. Please anyone tell me from where i get the view id for display the google analytics reports in chart format.

**Comment by bengtweisse** [comment]
Hey there,

Login to your analytics account.
In the header you have a navigation bar. Click on the last entry "Admin".
There you get an overview over all your accounts/properties and VIEWS.

Select your account then your property and in the last step your view.
In the "View" column you should click the first link "view settings".

Now you should see a settings overview of that view.

And nearly on top is:
Basic Settings
View ID:
8119xxxx

Hope that helps. If not ask again ;)

Greets.

**Comment by Mohinesh27** [comment]
Thank you very much its working.


[image: Flow Comptech Solutions] <http://www.flowcomptech.com/>
Mohinesh Tayade  | Project Manager
Flow Comptech Solutions | A/202, Mantri Lavendula, Paud Road, Bavdhan
Khurd, Pune, Maharashtra, India 411021
Mob: +91 8652078677,  9175694456
[image: WebsiteGB] <http://www.flowcomptech.com/>   [image: email]
<mohinesht@flowcomptech.com>
