### ISSUE TITLE
demo broken

### ISSUE THREAD

**Issue by donalmurtagh** [flyacts/ngAnalytics#11]
The demo fails because angular is not found at this path

    <script type="text/javascript" src="bower_components/angular/angular.min.js"></script>

Maybe you should change it to load angular from a CDN instead?

**Comment by KillerCodeMonkey** [comment]
maybe^^ in other cases run bower install.

if you use bower or npm the depencies are installed automatically

**Comment by donalmurtagh** [comment]
I think it would be an improvement if the demo worked out-of-the-box, but I guess that's not possible because you would still need to add your GA client ID to the source

**Comment by KillerCodeMonkey** [comment]
;)
