### ISSUE TITLE
Analytics Real Time Stats

### ISSUE THREAD

**Issue by macchie** [flyacts/ngAnalytics#12]
Hi there,
great work on this module, any idea on how i could implement realtime stats?

i mean rt:activeUsers metrics for example ;)

**Comment by KillerCodeMonkey** [comment]
It is enough to have the possibility to see all active users like here:
https://ga-dev-tools.appspot.com/embed-api/third-party-visualizations/

**Comment by KillerCodeMonkey** [comment]
@macchie 
please check out the feature branch
https://github.com/flyacts/ngAnalytics/tree/feature/activeUsers

and take a look in the demo page.. maybe this is enough.

i will documentate it if it is okay.

**Comment by macchie** [comment]
i will check i out ;) thanks

**Comment by KillerCodeMonkey** [comment]
i need to build custom analytics components for each metric so maybe active users are enough, yet ;)

**Comment by macchie** [comment]
ill take i look maybe i can help!

**Comment by macchie** [comment]
it works like a charm, thanks a lot
ill probably work on new feature, ill let you know! ;)

**Comment by KillerCodeMonkey** [comment]
Okay i will create a New release today
Am 08.09.2015 01:14 schrieb "Andrea Macchieraldo" <notifications@github.com
