### ISSUE TITLE
datepicker support

### ISSUE THREAD

**Issue by domurtag** [flyacts/ngAnalytics#13]
[This demo](https://ga-dev-tools.appspot.com/embed-api/custom-components/) show how to add start/end date pickers to a chart. It would be very useful if your library supported this, as a fixed range (e.g. last 30 days) is a bit inflexible.

**Comment by KillerCodeMonkey** [comment]
You can configure the dates within your queries ;) so you could add own datepicker and change your queries to get more data.

but feel free to extend this Module... it is opensource for that ;)
