### ISSUE TITLE
Fix for increase and decrease class in Active Users

### ISSUE THREAD

**Issue by macchie** [flyacts/ngAnalytics#17]
hi there again, may i suggest this modification to the onChange event in Active Users where the increase/decrease class is applied?

`animationClass = if data.delta > 0 then $scope.increaseClass or 'is-increasing' else if data.delta < 0 then $scope.decreaseClass or 'is-decreasing'`

with previous behaviour delta = 0 resulted in a decrease class application

cheers ;)

**Comment by KillerCodeMonkey** [comment]
i do not know if the change event is triggered if there is no delta?

**Comment by macchie** [comment]
it looks like it is triggered :/ in my app the class was applied even if there was no decrease

**Comment by KillerCodeMonkey** [comment]
changed it... try version 1.1.3
