### ISSUE TITLE
Server side authentication

### ISSUE THREAD

**Issue by psorensen** [flyacts/ngAnalytics#20]
Is it possible to authenticate server-side as per https://ga-dev-tools.appspot.com/embed-api/server-side-authorization/, but still use the directives included in this script?

**Comment by KillerCodeMonkey** [comment]
Ah, sorry the documentation is no complete.

the ngAnalyticsAuth-directive accepts a serviceAuthToken attribute, where you can pass your server token.

e.g.

```
<ng-analytics-auth label="Hallo:&nbsp;" service-auth-token="HERE_YOUR_TOKEN" hide-on-auth="true" auth-container="embed-api-auth-container"></ng-analytics-auth>
```

**Comment by psorensen** [comment]
Perfect. Thanks!

**Comment by KillerCodeMonkey** [comment]
Let me know if i can close the topic or close it on your own :)
