### ISSUE TITLE
Missing tags for v1.1.3/1.1.4

### ISSUE THREAD

**Issue by PeterDaveHello** [flyacts/ngAnalytics#21]
v1.1.3: https://github.com/flyacts/ngAnalytics/commit/5462d4f64053793971c05a8f6d1589376810875c
v1.1.4: https://github.com/flyacts/ngAnalytics/commit/1f07ae59b446cc321f89f045dccd21683b6a7016

**Comment by KillerCodeMonkey** [comment]
https://github.com/flyacts/ngAnalytics/tags ?

**Comment by PeterDaveHello** [comment]
Oh sorry, thanks for your prompt reply @KillerCodeMonkey, they were just hidden in [releases](https://github.com/flyacts/ngAnalytics/releases) page, my fault.

**Comment by KillerCodeMonkey** [comment]
no probs :+1:
