### ISSUE TITLE
ng-analytics-report is not getting displayed

### ISSUE THREAD

**Issue by prashant1989** [flyacts/ngAnalytics#22]
I am trying to use ng-analytics-report but nothing is visible.

Following is MY HTML code
```
<ng-analytics-report queries="queries" auth-container="embed-api-auth-container" view-selector-container="view-selector-container"></ng-analytics-report>
```

Following is my controller code
```
$scope.queries= [{
			reportType: 'ga',
			query: {
			 metrics: 'ga:sessions',
			dimensions: 'ga:city'
		}
	}];
```

Note: ng-analytics-chart is correctly getting rendered. 

Can you please help me to understand exactly what i am missing?

**Comment by KillerCodeMonkey** [comment]
reports are only data requests --> so nothing to visualize.

If a report was successfully this event is broadcasted:
`$rootScope.$broadcast('$gaReportSuccess', response, element);`

In error case
`$rootScope.$broadcast('$gaReportError', response, element);`

**Comment by prashant1989** [comment]
Thanks for your help
