### ISSUE TITLE
HTTPS cross domain scripting issue

### ISSUE THREAD

**Issue by josephclawrence** [flyacts/ngAnalytics#4]
Hi there

Firstly thanks very much for your work here :)

I'm wondering if this needs to be run on a domain with an SSL cert? When I try to load this up I get the following error:

Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://mydomain.com" from accessing a frame with origin "https://accounts.google.com".  The frame requesting access has a protocol of "http", the frame being accessed has a protocol of "https". Protocols must match.

Refused to display 'https://accounts.google.com/o/oauth2/auth?client_id=UA-464419-1&response_ty…igin=http%3A%2F%2Fclickshape.com&state=903540360%7C0.2500380857&authuser=0' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

Is there a way to run this code on a normal HTTP domain?

Thank you!

**Comment by KillerCodeMonkey** [comment]
Hey there,

First: Did you set your ClientId in the DemoPage?
`myAppModule.run(['ngAnalyticsService', function (ngAnalyticsService) {
                ngAnalyticsService.setClientId('YOUR API CLIENT ID HERE');
            }]);`
You have to setup google api for anayltics and create a client id to work with that api.
If that does not work i found something that says you simple can try to clean your cookies.

**Comment by josephclawrence** [comment]
Thanks very much, I was using an incorrect Client ID (Doh!)

**Comment by KillerCodeMonkey** [comment]
No probs
