### ISSUE TITLE
How to edit the view-selector-container?

### ISSUE THREAD

**Issue by tcervo** [flyacts/ngAnalytics#5]
I have everything working on a test site, but would like to edit the code that's generated for the selectors. The three selectors are currently generated in tables, and I'd like to use divs instead...but I can't find where that table code is being generated. If I look at the non-minified plugin, I see this:

templateUrl: 'ngAnalytics-view/template.html'

But nowhere do I find template.html.

**Comment by KillerCodeMonkey** [comment]
Hey,

all the stuff comes from google.
https://developers.google.com/analytics/devguides/reporting/embed/v1/component-reference

ngAnalytics is a wrapper to use the embed analytics api in your angularjs project a little bit easier.

So, google fills the dom-nodes with content to be sure, that the data is presented in the way they want.
But you can use Data Reports https://github.com/flyacts/ngAnalytics#report---ng-analytics-report 
to get only the information and format it your self.

Hope that helps.

**Comment by tcervo** [comment]
Yes, that helps. Thanks.

On Sun, Mar 22, 2015 at 11:50 PM, Bengt Weiße <notifications@github.com>
wrote:

> Hey,
>
> all the stuff comes from google.
>
> https://developers.google.com/analytics/devguides/reporting/embed/v1/component-reference
>
> ngAnalytics is a wrapper to use the embed analytics api in your angularjs
> project a little bit easier.
>
> So, google fills the dom-nodes with content to be sure, that the data is
> presented in the way they want.
> But you can use Data Reports
> https://github.com/flyacts/ngAnalytics#report---ng-analytics-report
> to get only the information and format it your self.
>
> Hope that helps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flyacts/ngAnalytics/issues/5#issuecomment-84843691>.
>



-- 
"What I believe is that all clear-minded people should remain two things
throughout their lifetimes: Curious and teachable." - Roger Ebert (RIP)
