### ISSUE TITLE
Refresh view call without a viewSelector?

### ISSUE THREAD

**Issue by mhomol** [flyacts/ngAnalytics#7]
This is more of a general question.  I reviewed the code but don't see where I can do this.  If I'm changing viewIDs myself and not using a viewSelector, is there a call to the controller or service that will ensure that the charts will refresh?  Just changing the viewIDs in the chart JSON does not appear to do it.

**Comment by KillerCodeMonkey** [comment]
This is not implemented, yet.
But a work around:
Destroy the DOM-Elements and rebuild them with the new viewID.
For that you can use ng-if.

Something like that:
Your init viewId
```$scope.query = {... ids: 'ga:81197147', ...};```

Now you want to change the id -> set a flag or reset our $scope.query
in your template you have something like that on your chart or report:
```.... ng-if="$scope.query"``` 
This will cause, that the elements will be removed from the dom

And after that you can set your $scope.query again with new ids.

Hope that helps and works ^^

**Comment by bengtweisse** [comment]
closed because of the good working workaround and very less interest^^
