### ISSUE TITLE
Area Chart

### ISSUE THREAD

**Issue by rseiffert** [flyacts/ngAnalytics#8]
First of all: Thank you for this nice and helpful ng implementation of the Analytics API!!

Right now, I am trying to implement an AREA-Chart, which is, as far as I know part of the Google corecharts. But regardless of what I try, I always get this:
Uncaught TypeError: Cannot read property 'libraries' of undefined

Question: Have you been succesful in implementing an AREA Chart? Even more stupid question: In your opinion: Do I use the right chart.type name:
chart: { type: 'AREA", ...}

**Comment by KillerCodeMonkey** [comment]
Hey, 
did you check if the demo-page worked with your account?

Your webspace / place of your HTML should be public and reachable for google.
In other cases the google-analytics library is not loaded.

AREA should be fine.. i think PIE, LINE are used in the same pattern

**Comment by rseiffert** [comment]
Hi, thanks for your answer. Yes every other supported charttype PIE, LINE, GEO, BAR, COLUMN works like a charm but not AREA :-(

**Comment by KillerCodeMonkey** [comment]
Strange, but i only find examples with pie and line Charts :( sorry
Am 29.05.2015 12:22 schrieb "rseiffert" <notifications@github.com>:

**Comment by sitek09** [comment]
Hi , first of all thanks for your code, easy, clean, perfect.

I have a question, its possible skip login process ? every day i try to check analytics report page request a login process, same when i use other pc or phone, my friends cant see those report too because they dont have my google username and password.

Its possible login automatically or skip this flow process?

Best regards.

**Comment by KillerCodeMonkey** [comment]
I think this is binded on your Browser and your Google sessions/cookies. If
you are already loggedin to the analytics account you shouldn't have to
login again. But if you switch the device or cleaned up your Browser data
or logged out of Google analytics. You have to login again. But maybe i am
missing something.

**Comment by donalmurtagh** [comment]
> Its possible login automatically or skip this flow process?

@KillerCodeMonkey @sitek09 If you use a service account for authentication it is not necessary for users to login to Google analytics. See these references

https://ga-dev-tools.appspot.com/embed-api/server-side-authorization/
https://github.com/flyacts/ngAnalytics/issues/10
