### ISSUE TITLE
Charts do not work without view-selector

### ISSUE THREAD

**Issue by camillef** [flyacts/ngAnalytics#9]
I am having trouble getting charts to work when I specify `ids: ga:XXXXX` myself.
I get a 400 Bad Request response with the error `message: "Required parameter: ids"`
even though my query contains a correct `ids` - I have checked with the Google Analytics Query Explorer and the query works fine here.

However, my charts do work when I include a view-selector and specify `view-selector-container="view-selector-container"` in my `ng-analytics-chart`.

Any ideas why this might be? Am I missing something?

The only idea I have is that I might be using an earlier version of Angular than required - but I am confused about why everything would work with the view-selector and not with a simpler query.

**Comment by KillerCodeMonkey** [comment]
Strange,... in my demopage this worked without connecting a viewSelector to the chart.

could you share your sourcecode, please?

**Comment by camillef** [comment]
I have copied the extraChart in your demo exactly, just replacing the `ids` with my own. 
It now seems to work the first time I open my web app, but after I refresh the page or move to a different view in my app the graph disappears - unless I change the auth container to a new one with a new name.

**Comment by camillef** [comment]
I've managed to fix this issue - it seemed to be a problem with scope, as I have a lot of different views in my app, I have now named the auth containers uniquely for every graph and it seems to work.

**Comment by KillerCodeMonkey** [comment]
thanks for your answer and feedback
